version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.4
  # different jobs are calles later in the workflows sections
jobs:
  build_test_deploy:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:14.17"
    steps:     
      - checkout
      - aws-cli/setup
      - eb/setup
      # install dependencies
      - run:
          name: Install Front-End and Back-End Dependencies
          command: npm run install        
      - run:
          name: Build Front-End and Back-End Projects
          command: npm run build
      # will only show log message
      - run:
          name: Test Front-End and Back-End Projects
          command: npm run test
      - run:
          name: Set Env Variables for EB
          command: npm run setEnvEB
      - run:
          name: Deploy App
          # Install, build, deploy in both apps
          command: npm run deploy
workflows:
  main_workflow:
    jobs:
      - build_test_deploy
        filters:
          branches:
            only: main
